Add github action rule for deployment

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -21,24 +21,22 @@ jobs:
           branch_name=$(echo ${{ github.event.release.target_commitish }} | cut -d/ -f2)
           if [[ "$branch_name" =~ ^release/.*$ ]]; then
             echo "Target branch is valid for deployment."
-            echo "::set-output name=valid_branch::true"
           else
-            echo "Invalid target branch. Skipping deployment."
-            echo "::set-output name=valid_branch::false"
+            echo "Error: Invalid target branch. Deployment aborted."
+            exit 1
           fi
 
       - name: Install Vercel CLI
-        if: steps.check-branch.outputs.valid_branch == 'true'
         run: npm install --global vercel
 
       - name: Pull Vercel Environment Information
-        if: steps.check-branch.outputs.valid_branch == 'true'
+        if: success()
         run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
 
       - name: Build Project Artifacts
-        if: steps.check-branch.outputs.valid_branch == 'true'
+        if: success()
         run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
 
       - name: Deploy Project Artifacts
-        if: steps.check-branch.outputs.valid_branch == 'true'
+        if: success()
         run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
